##By PC

server:
    port: 5588
    
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/pollos?useSSL=true
        username: root
        password: root
        testWhileIdle: true
        validationQuery: SELECT 1
        initialization-mode: always
        
    jpa:
        show-sql: true
        hibernate:
            ddl-auto: update
            properties:
                hibernate:
                    dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                    
                    
    jackson:
        serialization:
            WRITE_DATES_AS_TIMESTAMPS: false
        time-zone: UTC
        
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
            
        